# Generated by Django 5.2.11 on 2026-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalmZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('park', 'Parc/Jardin'), ('library', 'Bibliothèque'), ('quiet_street', 'Rue calme'), ('cafe', 'Café tranquille'), ('monument', 'Monument/Place')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('comfort_score', models.FloatField(default=0.8)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'calm_zones',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('max_crowd_density', models.FloatField(default=0.7)),
                ('avoid_main_roads', models.BooleanField(default=True)),
                ('prefer_parks', models.BooleanField(default=True)),
                ('noise_sensitivity', models.IntegerField(default=5)),
                ('walking_speed', models.FloatField(default=1.4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='CrowdDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('density', models.FloatField()),
                ('confidence', models.FloatField(default=0.8)),
                ('source', models.CharField(choices=[('sensor', 'Capteur'), ('prediction', 'Prédiction'), ('crowdsource', 'Crowdsourcing'), ('manual', 'Manuel')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crowd_data_points',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='crowd_data__latitud_5149f0_idx'), models.Index(fields=['timestamp'], name='crowd_data__timesta_33fd78_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('calculated_route', models.JSONField(blank=True, default=list)),
                ('stress_score', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'route_requests',
                'indexes': [models.Index(fields=['created_at'], name='route_reque_created_e594d5_idx')],
            },
        ),
    ]
