# Generated by Django 5.2.11 on 2026-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerequest',
            name='user_id',
            field=models.CharField(db_index=True, default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='routerequest',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='consider_public_transport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transport_factor',
            field=models.FloatField(default=0.15),
        ),
    ]
